LBM
paranumal/libparanumal pull request #71
Opened 2021-08-29 19:02 UTC by AliKarakus

DG / Lattice-Boltzmann solver with basic functionality.

2021-08-29 22:15 UTC, tcew reviewed
LGTM. 

Can you elaborate a bit on the difference to bns.

2021-08-30 12:47 UTC, AliKarakus commented
> LGTM.
> 
> Can you elaborate a bit on the difference to bns.

Both solvers govern the same physics and expecting to achieve similar results for low Mach flows. I think there are couple points of using DG- LBM, ​
--> it is very straight-forward to extend to different physics i.e. heat transfer, natural convection, multi-phase (I am working on connecting with Level-Set method for sharp interfaces) and multi-relaxation. 
​--> comparing  with BNS especially in boundary layers.
--> possible publications with extending to deforming meshes, pml, multi-phase, etc.

2021-09-06 16:09 UTC, noelchalmers commented on solvers/lbs/setups/setupQuad2D.rc
> +0.1
```suggestion
10.0
```

2021-09-06 16:10 UTC, noelchalmers commented on solvers/lbs/setups/setupTet3D.rc
> +0.1
```suggestion
10.0
```

2021-09-06 16:10 UTC, noelchalmers commented on solvers/lbs/setups/setupTri2D.rc
> +0.1
```suggestion
10.0
```

2021-09-06 16:11 UTC, noelchalmers commented on test/testLbs.py
> +               viscosity=0.01, velmodel="D2Q9", time_integrator="LSERK4", cfl=0.5, start_time=0.0, final_time=0.1,
```suggestion
               viscosity=0.01, velmodel="D2Q9", time_integrator="LSERK4", cfl=0.5, start_time=0.0, final_time=10.0,
```

2021-09-06 17:04 UTC, noelchalmers requested changes
This looks really good to me. A couple questions/comments:

- I think it's a good idea to make the default final time t=10 in the setup.rcs so that the runs produce several frames. 
- Same comment for the testing runs. Otherwise only a small number of timesteps are actually performed. (Changing this will require updated 'golden' norms).
- I suspect there is a subtle bug in the Quad2D code path. Running the default setup to t=10 doesn't pass the 'eyeball' norm. The Gaussian doesn't seem to move at all.

I see a several places where early PML and/or Multirate support is enabled/commented. @AliKarakus  is the plan to add these features in the future? They're not hurting anything so no worries either way. 

I also did some quick profiling on large problem setups. Probably unsurprisingly, several kernels are register heavy, the volume and phaseField kernels in particular are often at <30% peak DRAM BW. Not a problem, just an FYI. 

I second @tcew 's comment. I'm not particularly familiar with LBM, so it would be cool to see the full formulation written somewhere!

Thanks @AliKarakus !

2021-09-07 18:30 UTC, noelchalmers commented
@AliKarakus @tcew These test runs are going to be bitten by the latest OCCA changes complaining about `@barrier("local")`. Let ignore these test fails for the moment. 

Should we make occa a git submodule to avoid this kind of thing in the future?

2021-09-07 18:44 UTC, tcew commented
> Should we make occa a git submodule to avoid this kind of thing in the future?

Yes. I think this is a very good and timely idea. 

I anticipate quite a few changes in occa and we do not want to be continually held up.

2021-09-07 19:12 UTC, AliKarakus commented
@noelchalmers Thanks for the feedback, I double checked  all the tests on my local machine. Everything works smoothly. 

--> I see a several places where early PML and/or Multirate support is enabled/commented. @AliKarakus is the plan to add these features in the future? They're not hurting anything so no worries either way.

I am going to work on a PML formulation, but multi-rate time-stepping  creates some issues because of the time-step size dependent properties in LBM. Need to check details a little more.  Currently my target is to combine this basic DG-LBM formulation with Level-Set for bubble dynamics and contact line problems. 

--->I also did some quick profiling on large problem setups. Probably unsurprisingly, several kernels are register heavy, the volume and phaseField kernels in particular are often at <30% peak DRAM BW. Not a problem, just an FYI.

Yes, I think  this problem is arising from the high number of fields i.e. 9 for 2D and 15 or 19 for 3D.  At the moment, I don't know how to overcome this performance issue quickly  as BNS outperforms LBM even in 2D test cases. 

--->I'm not particularly familiar with LBM, so it would be cool to see the full formulation written somewhere!
It will be available soon (hopefully)  with DG-LBM/LS paper. 

Thanks a lot @noelchalmers and  @tcew .

2021-09-07 21:05 UTC, noelchalmers commented
@AliKarakus Can you merge the latest master branch? That should fix our OCCA issues and re-run the CI checks.

2021-09-07 21:38 UTC, tcew commented
@AliKarakus @noelchalmers - the Lbs tests seem to take quite a while. In particular the tet 3d case seems to take 20 minutes unless I misread the test report.

2021-09-07 21:43 UTC, noelchalmers approved these changes

2021-09-07 21:44 UTC, noelchalmers commented
LGTM. The whole suite of tests take around 24 minutes.

2021-09-07 21:48 UTC, tcew commented
> LGTM. The whole suite of tests take around 24 minutes.

@noelchalmers would you like to do the honors and merge this at your convenience ?

2021-09-07 21:49 UTC, merged

2021-09-07 21:50 UTC, tcew commented
Great work @AliKarakus and thanks to @noelchalmers for overseeing the merge !

2021-09-07 21:52 UTC, AliKarakus commented
Thanks @tcew and @noelchalmers. I am deleting the lbm branch now.